---
title: "Example Covid Report"
author: "INFO-201: Class Demo"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}


```

## Covid Report
I write a paragraph here. I will highlight that the total number of US cases is `r get_total_cases()`. And, the total number of US deaths is `r get_total_deaths()`. 

```{r kable_example, echo = FALSE}
library("knitr") # make sure you load the package (once per document)

# Make a data frame
data <- read.csv("/Users/daphnigeorge/Downloads/New_final_dataset - Sheet1.csv")
world_coordinates <- map_data("world")

world_coordinates <- rename(world_coordinates, Country = region)

data <- inner_join(x = data, y = world_coordinates, by = "Country")

summary_info <- list()
summary_info$num_observations <- nrow(data)
summary_info$some_max_value <- data %>% mutate_if(is.numeric, round) %>% group_by(Cost.of.Living.Index) %>%
    filter(Health.Care.Index == max(Health.Care.Index )) %>%
    select(Country,)

df <- data.frame(summary_info = summary_info, summary_info = summary_info)

# "Return" the table to render it

kable(summary_info)
```