---
title: "The Quality of Life in North and South America"
author: "Trisha, Daphni, Aradhana"
date: "11/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```
This bar graph depicts the crime and safety of countries in North and South America. The lower the crime rate, the higher safety a country has. The X axis is the crime index which shows the value of how much crime occured in each of the 17 countries. The Y is our dependent variable and represents the different countries in the South and North Amereica regions.The key on the right represents the safety index where it shows countries that are safest on the range from 20 to 50 above. The lighter the color, the more safer it is to live in.
Our map illustrates how easy it is to  access  healthcare in North and South America. The darker the region the harder it is for people to get heathcare and the lighter indicates easier acesability. 
This scatterplot indicates where each country stands within their cost of living index and their grocery index. A grocery index is an estimation of grocery prices in a given location compared to New York City. The cost of living index is the minimum amount of money it takes to live in that area. Some insights wee are able to see is that there is an upward trend within the countries cost of living and they are all rising consistently. With higher prices for groceries and higher cost of living it is harder for citizens to sustain in that country. 
```

## Charts

You can also embed plots, for example:

```{r raw_print_exampl, echo = FALSE} 
#bar graph 1
final_dataset <- read.csv("https://raw.githubusercontent.com/info201a-au2022/project-group-3-section-ae/main/data/New_final_dataset%20-%20Sheet1.csv")
#View(final_dataset)
library(dplyr)
library(ggplot2)
df_crime <- select(final_dataset, 1,4,5)
#View(df_crime)
my_bar_graph <- ggplot(df_crime, aes(x = Crime.Index, y = Country, fill = Safety.Index)) +
  geom_col() 
my_bar_graph + labs(title = "Crime and Safety in North & South America") +
  theme(plot.title = element_text(face="bold", size=15)) 
```
```{r raw_print_example, echo = FALSE}  
# map 2
library(ggplot2)
library(dplyr)
data <- read.csv("https://raw.githubusercontent.com/info201a-au2022/project-group-3-section-ae/main/data/New_final_dataset%20-%20Sheet1.csv")
world_coordinates <- map_data("world")
world_coordinates <- rename(world_coordinates, Country = region)
data <- inner_join(x = data, y = world_coordinates, by = "Country")
countryPlot <- ggplot()+geom_polygon(data=data,aes(x=long, y=lat, group = group, fill=Health.Care.Index))+coord_map()
print(countryPlot)
```
```{r raw_print_examp, echo = FALSE} 
#scatterplot 3
library(dplyr)
library(ggplot2)
cost_of_living <- read.csv("https://raw.githubusercontent.com/info201a-au2022/project-group-3-section-ae/main/data/New_final_dataset%20-%20Sheet1.csv")
#View(cost_of_living)
df_cost_of_living <- select (cost_of_living, 1,6,9)
#View(df_cost_of_living)
scatterplot <- ggplot(data=df_cost_of_living, aes(x=Groceries.Index, y=Cost.of.Living.Index))+
  geom_point()
scatterplot + labs(title = "                                Cost of Food in North and South America")
print(scatterplot)
```
```{r kable_example, echo = FALSE}
library("knitr") # make sure you load the package (once per document)
data <- read.csv("/Users/daphnigeorge/Downloads/New_final_dataset - Sheet1.csv")
data<- data %>% 
 mutate_if(is.numeric, round)
data <- data %>% group_by(Health.Care.Index) 
df <- data.frame( Health.Care.Index = data['Health.Care.Index'],Country = data["Country"], cost_of_living = data["Safety.Index"])
kable(df)
```