---
title: "Project Quality-Life"
author: "Daphni George, Trisha Thonupunoori, Aradhana Muthabatulla"
date: "11/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo  = FALSE}
# Example 1: Note relative path, which can be read: Up one
# directory(..), down into source (/source), and 
# then "source" an R file (data_access.R)
source("../source/Mychart.R")
da <- read.csv("https://raw.githubusercontent.com/info201a-au2022/project-group-3-section-ae/main/data/New_final_dataset%20-%20Sheet1.csv")
print(create(da))
```

### Chart 1: Healthcare Index Map
```
We included this map because it compared North and South American's Healthcare Index in an easy, clear manner. A note to keep in mind is that the Healthcare Index essentially is an estimate of the overall quality of the healthcare system. From the map above we can see that the worst healthcare index is present in South America. The South American continent overall has the worse healthcare indexes as we can tell from the darker colors. In North America intrestingly enough the United States has the worst Healthcare Index as shown by the darker hue.  
```


```{r echo  = FALSE}
# Example 1: Note relative path, which can be read: Up one
# directory(..), down into source (/source), and 
# then "source" an R file (data_access.R)
source("../source/graph.R")
da <- read.csv("https://raw.githubusercontent.com/info201a-au2022/project-group-3-section-ae/main/data/New_final_dataset%20-%20Sheet1.csv")
print(crime(da))
```

### Chart 2: Crime Index Bar Graph
```
We chose to include a bar graph for this dataset because it allows us to easily make observations about crime and safety rates of countries in North & South America. The lower the crime rate, the higher safety a country has. The X axis is the crime index which shows the value of how much crime occurred in each of the 17 countries. The Y is our dependent variable which represents the different countries to compare the crime rate and safety rate. The key on the right, safety index, shows a range of 20 to 50+ rates which illustrates the breakdown of colors where the lighter being the safest to live in. These components and information reveal that Panama has the lowest crime rate which means that it’s the safest to live in (highest rate of safety index).

```


```{r echo  = FALSE}
# Example 1: Note relative path, which can be read: Up one
# directory(..), down into source (/source), and 
# then "source" an R file (data_access.R)
source("../source/group project chart.R")
da <- read.csv("https://raw.githubusercontent.com/info201a-au2022/project-group-3-section-ae/main/data/New_final_dataset%20-%20Sheet1.csv")
print(cost_of_living(da))
```

### Chart 3: Cost of Living Scatter Plot
```
This scatterplot indicates where each country stands within their cost of living index and their grocery index. A grocery index is an estimation of grocery prices in a given location compared to New York City. The cost of living index is the minimum amount of money it takes to live in that area. Some insights wee are able to see is that there is an upward trend within the countries cost of living and they are all rising consistently. With higher prices for groceries and higher cost of living it is harder for citizens to sustain in that country. 

```
